version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8888:8080"
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - n1
  database:
    container_name: bamdoliro_gati_prod
    hostname: database
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - ${DB_PORT}:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - n1

  redis:
    image: redis:latest
    container_name: bamdoliro_gati_redis_prod
    hostname: ${REDIS_HOST}
    command: redis-server --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - n1

networks:
  n1:
