spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/bamdoliro_gati
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bamdoliro
    password: bamdoliro

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: asdfasdfasdfasfasdfadsfadsfasdfsadfsdfasfsfasdfsafasdfasdfasfasfasdsafsdffadsfasdfasfasf


  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

debug: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
---
spring:
  config:
    activate:
      on-profile: product


