spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://gati-database:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET}

  cache:
    type: redis

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

socket:
  config:
    port: ${SOCKET_PORT}